/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyCredentialIdRouteImport } from './routes/verify.$credentialId'
import { Route as PassportUsernameRouteImport } from './routes/passport.$username'
import { Route as NftIdRouteImport } from './routes/nft.$id'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedVerifyRouteImport } from './routes/_authenticated/verify'
import { Route as AuthenticatedSkillsRouteImport } from './routes/_authenticated/skills'
import { Route as AuthenticatedReputationRouteImport } from './routes/_authenticated/reputation'
import { Route as AuthenticatedQrRouteImport } from './routes/_authenticated/qr'
import { Route as AuthenticatedNftRouteImport } from './routes/_authenticated/nft'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated/admin.feedback'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCredentialIdRoute = VerifyCredentialIdRouteImport.update({
  id: '/verify/$credentialId',
  path: '/verify/$credentialId',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportUsernameRoute = PassportUsernameRouteImport.update({
  id: '/passport/$username',
  path: '/passport/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const NftIdRoute = NftIdRouteImport.update({
  id: '/nft/$id',
  path: '/nft/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerifyRoute = AuthenticatedVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsRoute = AuthenticatedSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReputationRoute = AuthenticatedReputationRouteImport.update({
  id: '/reputation',
  path: '/reputation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQrRoute = AuthenticatedQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNftRoute = AuthenticatedNftRouteImport.update({
  id: '/nft',
  path: '/nft',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/admin/feedback',
    path: '/admin/feedback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/recruiter': typeof RecruiterRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/nft': typeof AuthenticatedNftRoute
  '/qr': typeof AuthenticatedQrRoute
  '/reputation': typeof AuthenticatedReputationRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/nft/$id': typeof NftIdRoute
  '/passport/$username': typeof PassportUsernameRoute
  '/verify/$credentialId': typeof VerifyCredentialIdRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/recruiter': typeof RecruiterRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/nft': typeof AuthenticatedNftRoute
  '/qr': typeof AuthenticatedQrRoute
  '/reputation': typeof AuthenticatedReputationRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/nft/$id': typeof NftIdRoute
  '/passport/$username': typeof PassportUsernameRoute
  '/verify/$credentialId': typeof VerifyCredentialIdRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/recruiter': typeof RecruiterRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/nft': typeof AuthenticatedNftRoute
  '/_authenticated/qr': typeof AuthenticatedQrRoute
  '/_authenticated/reputation': typeof AuthenticatedReputationRoute
  '/_authenticated/skills': typeof AuthenticatedSkillsRoute
  '/_authenticated/verify': typeof AuthenticatedVerifyRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/nft/$id': typeof NftIdRoute
  '/passport/$username': typeof PassportUsernameRoute
  '/verify/$credentialId': typeof VerifyCredentialIdRoute
  '/_authenticated/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/feedback'
    | '/login'
    | '/recruiter'
    | '/scan'
    | '/signup'
    | '/welcome'
    | '/analytics'
    | '/certificates'
    | '/dashboard'
    | '/nft'
    | '/qr'
    | '/reputation'
    | '/skills'
    | '/verify'
    | '/wallet'
    | '/nft/$id'
    | '/passport/$username'
    | '/verify/$credentialId'
    | '/admin/feedback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/feedback'
    | '/login'
    | '/recruiter'
    | '/scan'
    | '/signup'
    | '/welcome'
    | '/analytics'
    | '/certificates'
    | '/dashboard'
    | '/nft'
    | '/qr'
    | '/reputation'
    | '/skills'
    | '/verify'
    | '/wallet'
    | '/nft/$id'
    | '/passport/$username'
    | '/verify/$credentialId'
    | '/admin/feedback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demo'
    | '/feedback'
    | '/login'
    | '/recruiter'
    | '/scan'
    | '/signup'
    | '/welcome'
    | '/_authenticated/analytics'
    | '/_authenticated/certificates'
    | '/_authenticated/dashboard'
    | '/_authenticated/nft'
    | '/_authenticated/qr'
    | '/_authenticated/reputation'
    | '/_authenticated/skills'
    | '/_authenticated/verify'
    | '/_authenticated/wallet'
    | '/nft/$id'
    | '/passport/$username'
    | '/verify/$credentialId'
    | '/_authenticated/admin/feedback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
  FeedbackRoute: typeof FeedbackRoute
  LoginRoute: typeof LoginRoute
  RecruiterRoute: typeof RecruiterRoute
  ScanRoute: typeof ScanRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
  NftIdRoute: typeof NftIdRoute
  PassportUsernameRoute: typeof PassportUsernameRoute
  VerifyCredentialIdRoute: typeof VerifyCredentialIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$credentialId': {
      id: '/verify/$credentialId'
      path: '/verify/$credentialId'
      fullPath: '/verify/$credentialId'
      preLoaderRoute: typeof VerifyCredentialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/$username': {
      id: '/passport/$username'
      path: '/passport/$username'
      fullPath: '/passport/$username'
      preLoaderRoute: typeof PassportUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nft/$id': {
      id: '/nft/$id'
      path: '/nft/$id'
      fullPath: '/nft/$id'
      preLoaderRoute: typeof NftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verify': {
      id: '/_authenticated/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthenticatedVerifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills': {
      id: '/_authenticated/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reputation': {
      id: '/_authenticated/reputation'
      path: '/reputation'
      fullPath: '/reputation'
      preLoaderRoute: typeof AuthenticatedReputationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qr': {
      id: '/_authenticated/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof AuthenticatedQrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nft': {
      id: '/_authenticated/nft'
      path: '/nft'
      fullPath: '/nft'
      preLoaderRoute: typeof AuthenticatedNftRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/feedback': {
      id: '/_authenticated/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNftRoute: typeof AuthenticatedNftRoute
  AuthenticatedQrRoute: typeof AuthenticatedQrRoute
  AuthenticatedReputationRoute: typeof AuthenticatedReputationRoute
  AuthenticatedSkillsRoute: typeof AuthenticatedSkillsRoute
  AuthenticatedVerifyRoute: typeof AuthenticatedVerifyRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNftRoute: AuthenticatedNftRoute,
  AuthenticatedQrRoute: AuthenticatedQrRoute,
  AuthenticatedReputationRoute: AuthenticatedReputationRoute,
  AuthenticatedSkillsRoute: AuthenticatedSkillsRoute,
  AuthenticatedVerifyRoute: AuthenticatedVerifyRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
  FeedbackRoute: FeedbackRoute,
  LoginRoute: LoginRoute,
  RecruiterRoute: RecruiterRoute,
  ScanRoute: ScanRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
  NftIdRoute: NftIdRoute,
  PassportUsernameRoute: PassportUsernameRoute,
  VerifyCredentialIdRoute: VerifyCredentialIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
